# Análisis de cambio semánticos (generar datos para análisis)

In [1]:
# Importar librería
from dotenv import load_dotenv
import pandas as pd
import numpy as np
import pickle
import os
import re
import random as rn
import datetime
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import bootstrap
import matplotlib.pyplot as plt
import itertools

from gensim.models import Word2Vec
from tqdm import tqdm
from sklearn.metrics.pairwise import cosine_similarity
tqdm.pandas()

from ast import literal_eval

In [2]:
# Configurar
load_dotenv() # Cargar las variables de entorno del archivo .env
BASE_DIR =  os.getenv("DIR_BASE")
RESULTADOS_DIR = os.getenv("DIR_DATOS_PROCESADOS") # Acceder a las variables de entorno modelos_swmwosge_1008211100
modelo_dir =  RESULTADOS_DIR+ '/archivos_out/modelos_swmwosge_5051100'
pd.set_option('display.max_colwidth', None)

Se selecciona para analizar el modelo de procrustes

In [3]:
basename = 'NN'
iteracion = 50
tam_vector = 50

In [4]:
# estabilidad_procrustes_iter10_tam50
selected_topics_df = pd.read_csv(
    modelo_dir+'/estabilidad_NN/estabilidad_'+basename+'_iter'+str(iteracion)+'_tam'+str(tam_vector)+'.csv',
    converters={'par_periodo': literal_eval})

selected_topics_df.sort_values('similaridad_semantica', ascending=True)

,iteracion,par_periodo,palabra,similaridad_semantica,cantidad_palabras_comun,topn_vecindad_t1,topn_vecindad_t2
65199,41,"(2009, 2014)",provincia,-25,25,"['prorrogable', 'neuquen', 'negro', 'departamento', 'santa', 'ochenta', 'localidad', 'desastre', 'plazo', 'rio', 'zona', 'diverso', 'aires', 'economico', 'termino', 'autonoma', 'ciudad', 'ciento', 'volcan', 'inundacion', 'consecuencia', 'productivo', 'potable', 'dengue', 'emergencia', 'junio', 'afectado', 'territorio']","['santa', 'rio', 'departamento', 'zona', 'localidad', 'negro', 'productivo', 'neuquen', 'desastre', 'prorrogable', 'ochenta', 'plazo', 'ciento', 'aires', 'inundacion', 'economico', 'volcan', 'ciudad', 'diverso', 'termino', 'junio', 'mes', 'autonoma', 'emergencia', 'consecuencia', 'afectado', 'infantil']"
65195,28,"(2009, 2014)",provincia,-25,25,"['departamento', 'negro', 'neuquen', 'prorrogable', 'ochenta', 'localidad', 'rio', 'santa', 'desastre', 'economico', 'plazo', 'diverso', 'aires', 'zona', 'termino', 'autonoma', 'ciudad', 'ciento', 'volcan', 'productivo', 'territorio', 'consecuencia', 'afectado', 'inundacion', 'junio', 'emergencia', 'hospital']","['santa', 'zona', 'departamento', 'localidad', 'rio', 'productivo', 'inundacion', 'desastre', 'plazo', 'negro', 'prorrogable', 'ochenta', 'ciudad', 'neuquen', 'aires', 'ciento', 'economico', 'volcan', 'diverso', 'mes', 'termino', 'autonoma', 'junio', 'emergencia', 'consecuencia', 'afectado']"
65198,33,"(2009, 2014)",cordoba,-25,25,"['ochenta', 'departamento', 'prorrogable', 'plazo', 'desastre', 'negro', 'economico', 'zona', 'neuquen', 'santa', 'consecuencia', 'afectado', 'diverso', 'rio', 'ciento', 'localidad', 'volcan', 'provincia', 'aires', 'inundacion', 'autonoma', 'termino', 'emergencia', 'productivo', 'junio', 'territorio', 'dengue', 'ciudad', 'declarar']","['productivo', 'departamento', 'desastre', 'zona', 'ciento', 'plazo', 'ochenta', 'localidad', 'diverso', 'neuquen', 'negro', 'santa', 'economico', 'rio', 'prorrogable', 'termino', 'provincia', 'aires', 'volcan', 'consecuencia', 'emergencia', 'inundacion', 'declarar', 'situacion', 'mes', 'junio', 'afectado']"
65197,44,"(2009, 2014)",cordoba,-25,25,"['ochenta', 'departamento', 'plazo', 'prorrogable', 'negro', 'desastre', 'neuquen', 'consecuencia', 'economico', 'zona', 'santa', 'provincia', 'ciento', 'localidad', 'rio', 'afectado', 'volcan', 'diverso', 'termino', 'aires', 'productivo', 'inundacion', 'autonoma', 'junio', 'dengue', 'emergencia', 'territorio', 'accidente', 'declarar', 'ciudad']","['productivo', 'departamento', 'zona', 'localidad', 'ciento', 'desastre', 'plazo', 'ochenta', 'diverso', 'negro', 'rio', 'neuquen', 'santa', 'economico', 'prorrogable', 'termino', 'provincia', 'aires', 'consecuencia', 'emergencia', 'volcan', 'inundacion', 'declarar', 'situacion', 'junio', 'autonoma', 'mes']"
65196,39,"(2009, 2014)",zona,-25,25,"['desastre', 'plazo', 'prorrogable', 'ochenta', 'volcan', 'departamento', 'aires', 'diverso', 'economico', 'emergencia', 'autonoma', 'negro', 'santa', 'provincia', 'neuquen', 'inundacion', 'localidad', 'productivo', 'termino', 'ciento', 'ciudad', 'rio', 'consecuencia', 'declarar', 'afectado', 'junio', 'dengue']","['productivo', 'desastre', 'departamento', 'plazo', 'ciento', 'ochenta', 'santa', 'prorrogable', 'rio', 'economico', 'localidad', 'neuquen', 'negro', 'provincia', 'volcan', 'diverso', 'inundacion', 'termino', 'situacion', 'aires', 'consecuencia', 'emergencia', 'mes', 'afectado', 'junio', 'declarar', 'ciudad']"
...,...,...,...,...,...,...,...
2703,7,"(2014, 2019)",dispongar,0,0,"['jubilado', 'modificacion', 'decreto', 'estudio', 'neonatal', 'agente', 'terapia', 'instituto', 'denominado', 'unico']","['dengue', 'prevenibl', 'virus', 'caracter', 'federal', 'zona', 'realizacion', 'economico']"
2702,22,"(2014, 2019)",congreso,0,0,"['economico', 'obligacion', 'clinica', 'aplicacion', 'discapacidad', 'zona', 'plazo', 'epidemiologico', 'hospital', 'clinico', 'digital', 'potable', 'relacion', 'grupo', 'cordoba']","['social', 'nacion', 'obra', 'entidad', 'prepagar', 'jubilado', 'situacion', 'modificacion', 'medicina', 'seguro']"
2701,22,"(2014, 2019)",politica,0,0,"['prevenibl', 'vacunacion', 'ingreso', 'habito', 'alimentacion', 'saludable', 'publicar', 'federal', 'comedor', 'dengue', 'desfibrilador', 'encontrar', 'control', 'endometriosis', 'adolescente', 'derogacion', 'fondo', 'instalacion', 'ciudadano', 'produccion']","['calidad', 'zona', 'declarese', 'prorrogable', 'cronico', 'termino', 'carbono', 'monoxido', 'vida', 'edad', 'economico', 'trombofilia', 'nutricion', 'declarar', 'sindrome', 'trastorno']"
2714,22,"(2014, 2019)",vino,0,0,"['hepatitis', 'trombofilia', 'sustancia', 'sindrome', 'vih']","['pmo', 'realizacion', 'alergia', 'demas']"
0,16,"(2009, 2014)",radiacion,0,0,"['perjudicial', 'efecto', 'diabetico', 'fondo', 'adolescente', 'apto', 'edad', 'tabaco', 'cancer', 'saludable', 'historia', 'victima']","['espacio', 'desfibrilador', 'leyenda', 'identificacion', 'celiaca', 'automatico', 'exhibicion', 'acceso', 'cualquiera', 'gluten', 'difusion', 'rehabilitacion', 'accidente', 'externo', 'contenido', 'diagnostico']"

In [5]:
selected_topics_df.describe() # Estadística

         iteracion  similaridad_semantica  cantidad_palabras_comun
count  65200.00000           65200.000000             65200.000000
mean      24.50000              -5.244340                 5.244340
std       14.43098               3.891113                 3.891113
min        0.00000             -25.000000                 0.000000
25%       12.00000              -7.000000                 3.000000
50%       24.50000              -5.000000                 5.000000
75%       37.00000              -3.000000                 7.000000
max       49.00000               0.000000                25.000000

Se realizaron 50 ejecuciones independientes del enfoque NN, cada una con una semilla aleatoria distinta. En cada iteración, se seleccionaron las 250 palabras con mayor cambio semántico entre los pares de períodos comparados, considerando únicamente aquellas con al menos 5 ocurrencias en alguno de los dos períodos de cinco años.

Posteriormente, se calculó la similaridad semantica promedio (medida de estabilidad del modelo) para cada palabra identificada en cada par de periodos comparados. Este valor fue estimado junto con sus respectivos intervalos de confianza del 95%, utilizando el método bootstrap.

In [6]:
n = 250
at_least_in_any_decade = 5
pares_periodo = [ (2009, 2014),(2014, 2019)]
topn_periodo = {}

for par_periodo in pares_periodo:
    df =  selected_topics_df[
        selected_topics_df['par_periodo'] == par_periodo
    ].copy()
    
    
    frecPer1 = pd.read_csv(RESULTADOS_DIR+'/archivos_out/frec_para_datos_limpios_por_desplaz_semantico_anios5_'+str(par_periodo[0])+'.csv')
    frecPer2 = pd.read_csv(RESULTADOS_DIR+'/archivos_out/frec_para_datos_limpios_por_desplaz_semantico_anios5_'+str(par_periodo[1])+'.csv')
    frecPer1.columns = ['palabra', 'frec1', 'porc1']
    frecPer2.columns = ['palabra', 'frec2', 'porc2']
    #print(frecPer2.shape)
    topn_all_df = []

    for iter in range(iteracion):
        #print(iter)
        df_topn = df[(df.iteracion==iter)]
        #controlar frec
        #display(df_topn)
        df_topn = df_topn.merge(frecPer1, how='left', on='palabra')
        df_topn = df_topn.merge(frecPer2, how='left', on='palabra')
        df_topn['max_freq_of_any_decade'] = df_topn[['frec1', 'frec2']].max(axis=1)
        df_topn.drop(['frec1', 'frec2', 'porc1', 'porc2'], axis=1, inplace=True) 
        df_topn = df_topn.loc[df_topn.max_freq_of_any_decade>= at_least_in_any_decade].head(n)
        df_topn = df_topn.sort_values('similaridad_semantica', ascending=True).head(n)
        #display(df_topn)
        topn_all_df.append(df_topn)
    
    topn_periodo[par_periodo] = pd.concat(topn_all_df, ignore_index=True)

#### Intersección promedio
Por el enfoque Procruste para cada par de periodos de 5 años:
¿Cuál es la similaridad semantica promedio (medida de estabilidad del modelo) de los top 250 palabras de las 50 ejecuciones para cada par de periodos comparados con intervalos de confianza del 95% calculados mediante el método bootstrap?

In [7]:
#def confidence_intervals(data):
#    res = bootstrap((data,), np.mean, confidence_level=0.95)
#    return (res.confidence_interval.low, res.confidence_interval.high)
def confidence_intervals(data):
    """
    Calcula intervalo de confianza con bootstrap de forma robusta
    """
    # Convertir a array numpy y limpiar NaN
    data_clean = np.array(data).copy()
    data_clean = data_clean[~np.isnan(data_clean)]
    
    # Casos especiales donde bootstrap no puede calcularse
    if len(data_clean) < 2:
        # Si hay solo un dato, no hay intervalo de confianza
        if len(data_clean) == 1:
            return (data_clean[0], data_clean[0])
        else:
            return (np.nan, np.nan)
    
    # Si todos los valores son iguales, bootstrap falla
    if np.all(data_clean == data_clean[0]):
        return (data_clean[0], data_clean[0])
    
    try:
        # Configurar bootstrap para evitar problemas con muestras pequeñas
        res = bootstrap(
            (data_clean,), 
            np.mean, 
            confidence_level=0.95,
            random_state=42,  # Para reproducibilidad
            n_resamples=min(1000, len(data_clean) * 100)  # Adaptar a tamaño de muestra
        )
        return (res.confidence_interval.low, res.confidence_interval.high)
    
    except (ValueError, RuntimeError):
        # Fallback: intervalo aproximado usando distribución t
        from scipy import stats
        n = len(data_clean)
        mean = np.mean(data_clean)
        std_err = stats.sem(data_clean)
        
        if n <= 1 or std_err == 0:
            return (mean, mean)
        
        h = std_err * stats.t.ppf((1 + 0.95) / 2., n - 1)
        return (mean - h, mean + h)

In [8]:
topn_periodo_all = topn_periodo.copy() # copiar

In [9]:
#df = topn_periodo[(2009, 2014)].copy()
#data = df['palabra'].value_counts().reset_index()
#data = data[data['count']>=2]
#pal_lista = list(data['palabra'].unique())
#df = df[df['palabra'].isin(pal_lista)]

# Convertir a listas si es necesario
#df['vt1'] = df['topn_vecindad_t1'].apply(lambda x: eval(x) if isinstance(x, str) else x)
#df['vt2'] = df['topn_vecindad_t2'].apply(lambda x: eval(x) if isinstance(x, str) else x)

# Agrupación simplificada
#def custom_agg(group):
#    return pd.Series({
#        'similaridad_mean': group['similaridad_semantica'].mean(),
#        'similaridad_ci': confidence_intervals(group['similaridad_semantica']),
#        'vt1_intersection': set.intersection(*map(set, group['vt1'])) if len(group) > 0 else set(),
#        'vt2_intersection': set.intersection(*map(set, group['vt2'])) if len(group) > 0 else set(),
#        'vt1_union': set.union(*map(set, group['vt1'])) if len(group) > 0 else set(),
#        'vt2_union': set.union(*map(set, group['vt2'])) if len(group) > 0 else set()
#    })

#df = df.groupby(['par_periodo', 'palabra']).apply(custom_agg).reset_index()

In [10]:
df

,iteracion,par_periodo,palabra,similaridad_semantica,cantidad_palabras_comun,topn_vecindad_t1,topn_vecindad_t2
2,17,"(2014, 2019)",exhibicion,0,0,"['tabaco', 'elaborado', 'cualquiera', 'distribucion', 'importacion', 'espacio', 'venta', 'expendio', 'publicitario', 'carbono', 'responsable', 'monoxido', 'gastronomico', 'difusion']","['desfibrilador', 'celiaco', 'obligatoriedad', 'ingreso', 'demas', 'estudio']"
3,33,"(2014, 2019)",adecuado,0,0,"['especialidad', 'medicinal', 'alimentario', 'codigo', 'potable', 'nutricional', 'braille', 'seguridad', 'alimentacion', 'producto']","['agente', 'situacion']"
4,40,"(2014, 2019)",suplemento,0,0,"['comercializacion', 'mujer', 'importacion', 'provision', 'monoxido', 'carbono', 'gratuito', 'misoprostol']","['libre', 'venta', 'prorrogable', 'sangre', 'publicidad', 'mes', 'tabaco', 'elaborado', 'leche', 'menor', 'etiquetado', 'donante', 'prohibicion', 'instalacion', 'trastorno', 'destinado']"
5,17,"(2014, 2019)",accion,0,0,"['mental', 'desarrollo', 'grupo', 'licenciado', 'demas', 'marzo', 'jubilado', 'sangre', 'prestacion', 'instituto', 'entidad', 'articulo', 'obra', 'red', 'marco', 'medicina']","['epidemiologico', 'promover', 'investigacion', 'educativo', 'inter', 'endometriosis', 'alergia', 'trombofilia', 'ciudadano', 'donacion', 'respuesta', 'padecer', 'tratamiento', 'capacitacion', 'declarar', 'medica']"
6,40,"(2014, 2019)",politica,0,0,"['prevenibl', 'vacunacion', 'ingreso', 'habito', 'control', 'alimentacion', 'fondo', 'derogacion', 'demas', 'federal', 'dengue', 'obra', 'produccion', 'saludable', 'virus', 'encontrar', 'comedor', 'institucion', 'destinado', 'escolar', 'adolescente']","['calidad', 'zona', 'declarese', 'prorrogable', 'termino', 'cronico', 'edad', 'carbono', 'trombofilia', 'monoxido', 'trastorno', 'economico', 'universal', 'cordoba', 'seguridad', 'infantil', 'sindrome']"
...,...,...,...,...,...,...,...
63299,16,"(2014, 2019)",capacitacion,-15,15,"['epidemiologico', 'reanimacion', 'cardiopulmonar', 'difusion', 'rcp', 'alergia', 'clinica', 'personal', 'digital', 'clinico', 'tecnica', 'investigacion', 'medica', 'deteccion', 'diagnostico', 'inter', 'hiperactividad', 'donacion', 'deficit', 'profesional', 'trombofilia', 'tdah', 'escolar', 'seguridad', 'patologia', 'promover']","['epidemiologico', 'cardiopulmonar', 'reanimacion', 'rcp', 'potable', 'escolar', 'alergia', 'materno', 'clinico', 'investigacion', 'administracion', 'clinica', 'anual', 'tecnica', 'profesional', 'medica', 'donacion', 'infantil', 'agua', 'implementacion', 'educativo', 'garantizar', 'deficit', 'bebida', 'diagnostico', 'situacion', 'obligatorio', 'nacido', 'gastronomico']"
63337,16,"(2014, 2019)",escolar,-16,16,"['asignacion', 'habito', 'adolescente', 'comedor', 'anual', 'reanimacion', 'federal', 'nina', 'saludable', 'deficit', 'edad', 'hiperactividad', 'alimentacion', 'tdah', 'nino', 'familiar', 'agente', 'proteccion', 'capacitacion', 'cardiopulmonar', 'difusion']","['reanimacion', 'cardiopulmonar', 'edad', 'rcp', 'comedor', 'educativo', 'capacitacion', 'trastorno', 'alimento', 'nino', 'difusion', 'tecnica', 'anual', 'deficit', 'hiperactividad', 'adolescente', 'nina', 'alimentacion', 'agente', 'tdah', 'nacido', 'destinado', 'saludable']"
63352,3,"(2014, 2019)",humano,-16,16,"['reproduccion', 'vih', 'asistido', 'prevenibl', 'banco', 'potable', 'hepatitis', 'tecnica', 'virus', 'alimenticio', 'infeccion', 'vacunacion', 'respuesta', 'derecho', 'consumo', 'agua', 'leche', 'apto', 'padecer', 'identificacion']","['agua', 'vih', 'potable', 'leche', 'reproduccion', 'etiquetado', 'banco', 'hepatitis', 'apto', 'infeccion', 'respuesta', 'virus', 'asistencial', 'asistido', 'red', 'consumo', 'alimenticio', 'externo', 'materno', 'instalacion', 'comercializacion', 'sangre', 'sustancia', 'privado', 'tecnica', 'padecer']"
63366,28,"(2014, 2019)",humano,-16,16,"['reproduccion', 'asistido', 'vih', 'banco', 'prevenibl', 'potable', 'tecnica', 'hepatitis', 'alimenticio', 'virus', 'infeccion', 'respuesta', 'leche', 'vacunacion', 'consumo', 'apto', 'padecer', 'red', 'identificacion', 'agua', 'codigo']","['leche', 'vih', 'potable', 'agua', 'hepatitis', 'etiquetado', 'apto', 'red', 'banco', 'reproduccion', 'materno', 'infeccion', 'respuesta', 'externo', 'instalacion', 'provincia', 'virus', 'asistencial', 'tecnica', 'asistido', 'consumo', 'alimenticio', 'sexual', 'sustancia', 'instituto', 'terapeutico']"
63373,8,"(2014, 2019)",humano,-16,16,"['reproduccion', 'asistido', 'potable', 'banco', 'prevenibl', 'vih', 'hepatitis', 'infeccion', 'tecnica', 'virus', 'leche', 'alimenticio', 'vacunacion', 'consumo', 'respuesta', 'identificacion', 'agua', 'etiquetado', 'regulacion', 'derecho', 'apto']","['etiquetado', 'vih', 'agua', 'potable', 'leche', 'reproduccion', 'apto', 'banco', 'infeccion', 'hepatitis', 'instalacion', 'virus', 'acceso', 'red', 'respuesta', 'externo', 'comercializacion', 'materno', 'tecnica', 'alimenticio', 'asistido', 'provincia', 'sexual', 'consumo', 'sustancia']"

In [11]:
#df = topn_periodo[(2009, 2014)].copy()
#data = df['palabra'].value_counts().reset_index()
#data = data[data['count']<2]
#pal_lista = list(data['palabra'].unique())
#pal_lista
# (2009, 2014) = ['tratamiento',  'provincia',  'desastre',  'celula', 'pmo', 'ministerio', 'zona', 'ambito']
#(2014, 2019) = ['nina', 'persona', 'medicina', 'potable', 'ley']

In [12]:
for par_periodo in pares_periodo: 
    display(topn_periodo[par_periodo].shape)
    df = topn_periodo[par_periodo].copy()
    data = df['palabra'].value_counts().reset_index()
    data = data[data['count']>=2]
    pal_lista = list(data['palabra'].unique())
    df = df[df['palabra'].isin(pal_lista)]

    # Convertir a listas si es necesario
    df['vt1'] = df['topn_vecindad_t1'].apply(lambda x: eval(x) if isinstance(x, str) else x)
    df['vt2'] = df['topn_vecindad_t2'].apply(lambda x: eval(x) if isinstance(x, str) else x)

    # Agrupación simplificada
    def custom_agg(group):
        return pd.Series({
            'similaridad_semantica_mean': group['similaridad_semantica'].mean(),
            'similaridad_ci': confidence_intervals(group['similaridad_semantica']),
            'vt1': set.intersection(*map(set, group['vt1'])) if len(group) > 0 else set(),
            'vt2': set.intersection(*map(set, group['vt2'])) if len(group) > 0 else set(),
            'vt1_union': set.union(*map(set, group['vt1'])) if len(group) > 0 else set(),
            'vt2_union': set.union(*map(set, group['vt2'])) if len(group) > 0 else set()
        })

    df = df.groupby(['par_periodo', 'palabra']).apply(custom_agg).reset_index()
    topn_periodo[par_periodo] = df

(12500, 8)

C:\Users\Usuario\AppData\Local\Temp\ipykernel_2392\1069459452.py:24: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df = df.groupby(['par_periodo', 'palabra']).apply(custom_agg).reset_index()

(12500, 8)

C:\Users\Usuario\AppData\Local\Temp\ipykernel_2392\1069459452.py:24: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df = df.groupby(['par_periodo', 'palabra']).apply(custom_agg).reset_index()

In [13]:
topn_periodo[par_periodo].head(3)

,par_periodo,palabra,similaridad_semantica_mean,similaridad_ci,vt1,vt2,vt1_union,vt2_union
0,"(2014, 2019)",academia,-0.240000,"(-0.38, -0.14)","{deportivo, desfibrilador, externo, institucion, preventivo, centro}","{medica, decreto, cordoba}","{actividad, evaluacion, obligatoriedad, externo, institucion, espacio, personal, establecimiento, automatico, equipo, apto, provision, privado, equinoterapia, desfibrilador, preventivo, centro, reproduccion, potable, deportivo, gastronomico, certificado, oncologico, practica, educativo}","{semana, instituir, marzo, especialidad, elaborado, inclusion, tdah, vih, infeccion, derogacion, tabaco, clinico, equinoterapia, medicinal, epidemiologico, misoprostol, derivado, educacion, visual, decreto, ejercicio, cordoba, zona, reproduccion, hiperactividad, licenciado, receta, medica, articulo, diabetes}"
1,"(2014, 2019)",accesibilidad,-0.660000,"(-0.88, -0.48)","{espacio, equinoterapia, prepagar}",{gratuito},"{historia, grupo, relacion, terapia, vacunacion, encontrar, rehabilitacion, espacio, prevenibl, endometriosis, automatico, prepagar, equinoterapia, beneficio, integral, desfibrilador, asistido, donante, proteccion, codigo, reproduccion, potable, asignacion, obra, fondo, adolescente, terapeutico, garantizar, marco, administracion, medicina, seguro, publico, universal, acceso, seguridad, ingreso, persona, braille}","{historia, recien, externo, rehabilitacion, elaborado, espacio, envase, incorporar, comercializacion, prevenibl, tabaco, menor, condicion, instalacion, respuesta, provision, equinoterapia, celiaco, producto, visual, hepatitis, desfibrilador, embarazado, argentino, donante, preventivo, patologia, neonatal, centro, libre, potable, estudio, agua, alimenticio, certificado, licenciado, pesquisa, banco, gratuito, practica, braille, virus}"
2,"(2014, 2019)",accidente,-3.860465,"(-4.093023255813954, -3.627906976744186)","{carbono, vida, monoxido, responsable, sustancia, rehabilitacion}","{monoxido, carbono, alergia, campana}","{semana, fibromialgia, concientizacion, sustancia, rehabilitacion, campana, utilizacion, sindrome, vih, elaborado, diabetes, prevenibl, distribucion, tabaco, vida, monoxido, lucha, derivado, carbono, prevencion, publicitario, responsable, paciente, alto, preventivo, mes, promover, victima, riesgo, oncologico, dengue, cualquiera}","{termino, semana, evaluacion, mujer, marzo, vacunacion, fibromialgia, alergia, campana, ciudadano, sindrome, control, prevenibl, endometriosis, difusion, vida, regulatorio, plan, anual, monoxido, leche, trombofilia, nacido, epidemiologico, carbono, hepatitis, embarazado, prevencion, publicitario, deteccion, cronico, victima, implementacion, infantil, pesquisa, diagnostico, programa, argentina, tratamiento, oncologico, violencia}"

### Cambios semánticos  

#### Identificar las palabras con cambio semántico importante y moderado

In [14]:
# GUARDAR OBJETO
with open(modelo_dir+'/top250_periodos_NN_df.pkl', 'wb') as file: 
    pickle.dump(topn_periodo,file)

In [15]:
topk = 10
for par_periodo in pares_periodo:

   
    periodo_df = topn_periodo[par_periodo]
    umbral_fuerte1 = 0.3
    periodo_df1 =  periodo_df.sort_values('similaridad_semantica_mean', ascending=True).head(topk)
    # Graficar Heatmaps
    #display(periodo_df1)
    #plot_heatmap(periodo_df1[['palabra','similaridad_semantica_mean']], "Cambio semántico  (["+str(par_periodo[0])+"-"+str(par_periodo[1])+") → ["+str(par_periodo[1])+"-"+str(par_periodo[1]+5)+")", top=topk)
    print("TOP 10 Palabras:", periodo_df1['palabra'].unique())
    display(periodo_df1)

TOP 10 Palabras: ['humano' 'pensionado' 'diagnostico' 'gluten' 'institucion' 'lectivo'
 'nacido' 'instituir' 'destinado' 'especial']

,par_periodo,palabra,similaridad_semantica_mean,similaridad_ci,vt1,vt2,vt1_union,vt2_union
145,"(2009, 2014)",humano,-7.000000,"(-7, -7)","{desarrollo, sexual, hepatitis, vacunacion, asistido, leche, responsable, poblacion, materno, promover, tecnica, acceso, virus, vacuna, reproduccion}","{potable, leyenda, identificacion, alimenticio, hepatitis, vacunacion, asistido, leche, tecnica, beneficiario, virus, reproduccion}","{evaluacion, donacion, vacunacion, concientizacion, aplicacion, inclusion, investigacion, anual, leche, poblacion, materno, politica, nacido, desarrollo, octubre, educacion, pmo, hepatitis, decreto, asistido, responsable, vacuna, reproduccion, promover, sexual, anos, publicidad, administracion, padecer, medicina, medica, seguro, tecnica, gratuito, acceso, movil, tipo, virus}","{derecho, vacunacion, produccion, consumo, identificacion, alimento, desastre, leche, apto, beneficiario, forma, hepatitis, asistido, virus, regulacion, reproduccion, potable, agua, alimenticio, prohibir, tecnica, leyenda}"
228,"(2009, 2014)",pensionado,-7.000000,"(-7, -7)","{instituto, establecer, instituir, jubilado, servicio, beneficiario, administracion, sexo, ciudadano, seguridad, diabetes}","{instituto, octubre, instituir, jubilado, servicio, beneficiario, sexo, minimo, edad, diabetes, cuyo}","{establecer, instituir, evaluacion, jubilado, hijo, sexo, ciudadano, rehabilitacion, elaborado, nina, vida, pais, beneficiario, celiaco, instituto, unico, decreto, sistema, escolar, junio, social, potable, asignacion, servicio, administracion, universal, seguridad, movil, diabetes}","{productivo, instituir, jubilado, hijo, encontrar, sexo, edad, vida, plazo, cuyo, prepagar, ochenta, beneficiario, instituto, octubre, beneficio, sangre, modificacion, respectivamente, reproduccion, aires, servicio, ciento, minimo, diabetes, ano}"
85,"(2009, 2014)",diagnostico,-6.875000,"(-7.0, -6.375)","{celiaca, difusion, pmo, hepatitis, medica, tratamiento, deteccion, campana, capacitacion, psoriasis, enfermedad}","{difusion, integral, hepatitis, mujer, seguimiento, tratamiento, deteccion, capacitacion, psoriasis}","{trastorno, terapia, produccion, medico, campana, investigacion, incorporar, comercializacion, difusion, plan, anual, cancer, forma, clinico, enfermedad, medicinal, celiaco, examen, desarrollo, inter, pmo, gluten, hepatitis, asistido, deteccion, cronico, capacitacion, psoriasis, celiaca, estudio, implementacion, asistencia, medica, padecer, tratamiento, contener}","{inter, integral, hepatitis, obligatorio, mujer, embarazado, cobertura, recien, deteccion, paciente, capacitacion, psoriasis, investigacion, celiaca, incorporar, estudio, difusion, seguimiento, programa, tratamiento, lucha}"
137,"(2009, 2014)",gluten,-6.857143,"(-7.0, -6.428571428571429)","{envase, celiaca, identificacion, alimenticio, producto, alimento, venta, diabetico, bebida, rotulo, sustancia, apto, elaborado, contener, leyenda, contenido, celiaco}","{envase, celiaca, identificacion, alimenticio, economico, publicar, leyenda, contenido, especial}","{destinado, perjudicial, terapia, sustancia, especialidad, elaborado, contenido, envase, identificacion, tabaco, alimento, importacion, rotulo, apto, medicinal, celiaco, producto, venta, diabetico, psoriasis, exhibicion, celiaca, bebida, alimenticio, padecer, contener, leyenda, cuyo}","{productivo, publicar, donante, aplicacion, registro, contenido, especial, entidad, envase, celiaca, identificacion, alimenticio, asistencial, ciento, prohibir, economico, desastre, movil, hospital, leyenda, celiaco}"
163,"(2009, 2014)",institucion,-6.666667,"(-7.0, -6.0)","{deportivo, historia, automatico, desfibrilador, pais, embarazado, derecho, recien, inciso, caracter, profesional, modificacion, externo, paciente, espacio, clinico, junio}","{deportivo, automatico, desfibrilador, diabetico, pais, caracter, externo, cualquiera}","{historia, derecho, recien, vacunacion, caracter, externo, espacio, automatico, pais, inciso, clinico, diverso, neuquen, desfibrilador, embarazado, profesional, modificacion, ejercicio, paciente, junio, deportivo, garantizar, familiar, universal, articulo, departamento}","{desfibrilador, diabetico, donacion, sangre, ciudad, caracter, externo, paciente, centro, especial, deportivo, alimenticio, automatico, adolescente, pais, alimentacion, politica, clinico, diabetes, cualquiera}"
172,"(2009, 2014)",lectivo,-6.666667,"(-7.0, -6.0)","{octubre, droga, plazo, instituir, diabetes, implementar, mundial, campana, cancer, departamento, junio, lucha, ano}","{octubre, dengue, implementar, mundial, campana, junio, lucha, mes}","{droga, instituir, sexo, campana, plazo, ochenta, desastre, economico, cancer, lucha, octubre, implementar, mundial, cronico, junio, respectivamente, adolescente, negro, ciento, departamento, diabetes, ano}","{octubre, lucha, implementar, mundial, ciudadano, campana, junio, diabetes, mes, dengue, accidente}"
204,"(2009, 2014)",nacido,-6.636364,"(-6.909090909090909, -6.2727272727272725)","{nino, estudio, implementacion, anos, examen, recien, asistido, modificacion, anual, diverso, reproduccion}","{nino, estudio, recien, seguimiento, anual, diverso, situacion, examen}","{informacion, mujer, hijo, rio, recien, registro, campana, nina, inciso, rotulo, anual, poblacion, medicinal, diverso, examen, nino, embarazado, modificacion, asistido, reproduccion, estudio, celiaca, asignacion, anos, implementacion, adolescente, familiar, seguro, tecnica, acceso}","{nino, hijo, recien, caracter, deteccion, edad, escolar, zona, nina, estudio, sexual, asignacion, implementacion, negro, seguimiento, anual, localidad, diverso, situacion, examen}"
164,"(2009, 2014)",instituir,-6.500000,"(-6.833333333333333, -6.166666666666667)","{octubre, infantil, droga, jubilado, ciudad, concientizacion, mundial, argentino, autonoma, pensionado, escolar, cancer, departamento, junio, respectivamente, mes, ano}","{octubre, diabetico, mujer, jubilado, sangre, pensionado, junio, lucha, mes, ano}","{provincia, droga, jubilado, caracter, concientizacion, sexo, alimentario, campana, promocion, difusion, plazo, economico, movil, cancer, instituto, octubre, implementar, mundial, ciudad, argentino, autonoma, pensionado, codigo, escolar, junio, respectivamente, mes, potable, nutricional, infantil, aires, negro, seguridad, departamento, hospital, ano}","{historia, mujer, jubilado, donacion, plazo, prorrogable, beneficiario, lucha, octubre, diabetico, sangre, donante, pensionado, inundacion, capacitacion, junio, mes, victima, infantil, servicio, nacional, universal, diabetes, ano}"
82,"(2009, 2014)",destinado,-6.500000,"(-7.0, -6.0)","{perjudicial, hijo, encontrar, edad, nina, tabaco, consecuencia, apto, politica, gluten, virus, celiaca, alimenticio, asistencial, bebida, fondo, adolescente, volcan, calidad, leyenda, cuyo}","{actividad, produccion, consumo, nina, comercializacion, vida, instalacion, consecuencia, nino, producto, desfibrilador, embarazado, humano, escolar, alimenticio, adolescente, prohibir, obligacion, contener}","{perjudicial, evaluacion, hijo, encontrar, sexo, sustancia, edad, leyenda, nina, tabaco, impuesto, pais, menor, consecuencia, apto, politica, inter, producto, gluten, diabetico, regulacion, celiaca, asignacion, alimenticio, asistencial, bebida, fondo, adolescente, volcan, universal, calidad, virus, cuyo}","{actividad, encontrar, produccion, consumo, rehabilitacion, edad, especial, nina, envase, comercializacion, vida, menor, instalacion, consecuencia, seguimiento, importacion, politica, nino, producto, desfibrilador, diabetico, embarazado, humano, escolar, capacitacion, alimenticio, adolescente, prohibir, publicidad, obligacion, contener, leyenda, cualquiera}"
112,"(2009, 2014)",especial,-6.500000,"(-7.0, -6.0)","{educacion, asistencia, atencion, fondo, diabetico, donacion, inundacion, cuidado, entidad, victima}","{alimenticio, asistencia, alimento, fondo, diabetico, alimentacion, donacion, gluten, ciudad, donante, nutricion, situacion}","{historia, donacion, ambito, alimentario, registro, entidad, alimento, desastre, apto, privado, emergencia, politica, clinico, unico, educacion, atencion, diabetico, autonoma, inundacion, paciente, cuidado, zona, victima, promover, nutricional, asistencia, fondo, aires, situacion}","{provincia, historia, trastorno, donacion, alimentario, aplicacion, institucion, espacio, entidad, contenido, identificacion, alimento, politica, santa, gluten, diabetico, profesional, sangre, ciudad, donante, nutricion, victima, nutricional, asignacion, alimenticio, asistencia, fondo, adolescente, alimentacion, situacion}"

TOP 10 Palabras: ['masivo' 'ano' 'anti' 'numerir' 'nacional' 'santa' 'provision' 'banco'
 'provincia' 'mes']

,par_periodo,palabra,similaridad_semantica_mean,similaridad_ci,vt1,vt2,vt1_union,vt2_union
199,"(2014, 2019)",masivo,-5.25,"(-5.92317645169422, -5.0)","{derivado, gastronomico, difusion, carbono, automatico, desfibrilador, instalacion, monoxido, publicitario, externo, privado, espacio, educativo}","{gastronomico, difusion, donacion, realizacion, neonatal}","{derivado, carbono, desfibrilador, concientizacion, publicitario, externo, espacio, gastronomico, difusion, automatico, cardiopulmonar, instalacion, monoxido, publico, privado, educativo}","{carbono, atencion, hepatitis, desfibrilador, donacion, saludable, publicitario, aplicacion, realizacion, capacitacion, neonatal, investigacion, promover, potable, gastronomico, difusion, agua, automatico, anual, monoxido, privado, seguridad, epidemiologico, educativo}"
19,"(2014, 2019)",ano,-5.00,"(-5, -5)","{semana, instituir, marzo, mundial, mes}","{termino, semana, instituir, marzo, menor, prorrogable, mes}","{semana, trastorno, instituir, mujer, marzo, jubilado, fibromialgia, realizacion, edad, sindrome, declarese, menor, monoxido, lucha, carbono, venta, atencion, embarazado, sangre, mundial, argentino, mes, promover, nutricional, gastronomico, anos, infantil, cardiopulmonar, legal, reanimacion, padecer, diabetes, rcp}","{termino, provincia, semana, historia, instituir, marzo, vacunacion, concientizacion, alimentario, edad, vih, infeccion, nina, endometriosis, embarazo, plazo, menor, anual, monoxido, prorrogable, cancer, territorio, lucha, enfermedad, expendio, inter, carbono, integral, declarar, mundial, cordoba, mes, zona, bebida, universal, dengue, virus}"
20,"(2014, 2019)",anti,-5.00,"(-5, -5)","{infeccion, hepatitis, diagnostico, caracter, argentina, realizacion, vih, trombofilia}","{hepatitis, caracter, monoxido, anual, realizacion, vih, virus}","{semana, hepatitis, embarazado, caracter, realizacion, vih, sindrome, reproduccion, infeccion, incorporar, cardiopulmonar, republica, argentina, diagnostico, reanimacion, trombofilia, virus, rcp}","{carbono, hepatitis, recien, caracter, nacido, alergia, realizacion, sindrome, vih, potable, prevenibl, infeccion, pesquisa, anual, monoxido, dengue, virus}"
233,"(2014, 2019)",numerir,-5.00,"(-5, -5)","{distribucion, tabaco, modificacion, importacion, publicidad, banco, elaborado, promocion, etiquetado, cualquiera}","{prohibicion, expendio, comercializacion, tabaco, alimenticio, producto, modificacion, publicidad, codigo, elaborado, utilizacion, espacio, etiquetado, libre}","{venta, modificacion, consumo, elaborado, promocion, etiquetado, distribucion, tabaco, importacion, publicidad, banco, leche, cualquiera}","{expendio, producto, sangre, modificacion, codigo, elaborado, utilizacion, espacio, etiquetado, libre, prohibicion, comercializacion, tabaco, alimenticio, licenciado, publicidad}"
226,"(2014, 2019)",nacional,-5.00,"(-5, -5)","{red, clinica, educacion, nacion, ministerio, declarar, federal, dengue, epidemiologico}","{carbono, infantil, ministerio, evaluacion, declarese, ambito, programa, monoxido, prorrogable, cancer, creacion, zona}","{red, establecer, instituir, jubilado, promocion, clinica, nacion, ministerio, declarese, deficit, federal, emergencia, cancer, enfermedad, epidemiologico, inter, instituto, educacion, atencion, integral, declarar, digital, prevencion, deteccion, creacion, respectivamente, hospital, implementacion, infantil, alimentacion, programa, medica, persona, violencia, dengue, regimen}","{evaluacion, marzo, derecho, ambito, concientizacion, vih, promocion, infeccion, endometriosis, ministerio, declarese, plan, anual, monoxido, prorrogable, materno, cancer, sanitario, lucha, inter, nino, carbono, integral, hepatitis, declarar, prevencion, creacion, patologia, zona, sexual, implementacion, infantil, marco, programa, precio, persona, diabetes, situacion}"
318,"(2014, 2019)",santa,-5.00,"(-5, -5)","{termino, provincia, plazo, zona, economico, consecuencia, prorrogable, cordoba, mes, situacion}","{misoprostol, provincia, plazo, cordoba, prorrogable, dengue, zona}","{termino, provincia, afectado, cordoba, mes, zona, plazo, economico, consecuencia, prorrogable, emergencia, situacion}","{misoprostol, provincia, decreto, vih, afectado, cordoba, zona, plazo, prorrogable, dengue, complementario}"
293,"(2014, 2019)",provision,-5.00,"(-5, -5)","{potable, agua, deportivo, asistencial, garantizar, gratuito, diabetes, centro}","{potable, deportivo, agua, jubilado, gratuito, apto, comedor, centro}","{establecer, derecho, vacunacion, consumo, alergia, institucion, personal, establecimiento, prevenibl, desfibrilador, publicar, codigo, paciente, centro, libre, potable, agua, deportivo, asistencial, gastronomico, legal, servicio, garantizar, gratuito, acceso, diabetes}","{grupo, jubilado, caracter, consumo, elaborado, tdah, inclusion, entidad, establecimiento, nina, comercializacion, identificacion, tabaco, alimento, embarazo, deficit, condicion, equipo, apto, comedor, privado, trombofilia, expendio, nino, misoprostol, derivado, producto, desfibrilador, responsable, cuidado, patologia, centro, potable, deportivo, agua, bebida, anos, hiperactividad, gastronomico, cardiopulmonar, legal, precio, medica, padecer, gratuito, tecnica, oncologico, acceso, virus, rcp}"
35,"(2014, 2019)",banco,-5.00,"(-5, -5)","{red, leche, humano, materno}","{red, terapeutico, sangre, pesquisa, instalacion, menor, donacion, leche, donante, materno, obligacion, neonatal}","{red, produccion, consumo, sustancia, registro, elaborado, alergia, entidad, infeccion, tabaco, nacion, ministerio, leche, materno, producto, pmo, hepatitis, modificacion, digital, responsable, humano, etiquetado, vacuna, reproduccion, alimenticio, padecer, dengue}","{red, historia, mujer, donacion, vacunacion, registro, campana, alergia, vih, comercializacion, difusion, ministerio, menor, instalacion, leche, materno, producto, hepatitis, sangre, donante, humano, respectivamente, habito, patologia, neonatal, victima, etiquetado, potable, bebida, anos, infantil, asistencial, terapeutico, garantizar, pesquisa, obligacion}"
292,"(2014, 2019)",provincia,-5.00,"(-5, -5)","{termino, plazo, economico, prorrogable, cordoba, mes, zona}","{termino, nutricional, dengue, economico, prorrogable, federal, afectado, cordoba, zona}","{termino, declarar, alto, cordoba, habito, mes, zona, neonatal, plazo, economico, consecuencia, prorrogable, emergencia, violencia, sanitario, situacion}","{termino, misoprostol, declarar, vih, afectado, cordoba, zona, vacuna, nutricional, hospital, economico, prorrogable, federal, emergencia, privado, dengue, virus}"
209,"(2014, 2019)",mes,-5.00,"(-5, -5)","{semana, plazo, instituir, marzo, prorrogable}","{termino, endometriosis, semana, carbono, instituir, decreto, marzo, recien, anual, monoxido, nacido}","{termino, provincia, semana, educacion, instituir, marzo, concientizacion, cordoba, zona, plazo, prorrogable, violencia, ano}","{termino, semana, carbono, trastorno, instituir, decreto, marzo, recien, realizacion, afectado, cordoba, zona, denominado, endometriosis, asignacion, prepagar, anual, monoxido, prorrogable, dengue, nacido, ano}"

Palabras comunes entre los pares de períodos

In [18]:
# palabra común en entre períodos
palabra_comun = set(topn_periodo[(2009, 2014)]['palabra'].unique()) & set(topn_periodo[(2014, 2019)]['palabra'].unique())
print("Cantidad de palabras en común:",len(palabra_comun))

Cantidad de palabras en común: 234

Top 10

In [29]:
# Período (2009, 2014)
df = topn_periodo[(2009, 2014)]
df = df[df['palabra'].isin(palabra_comun)]
df = df[['palabra','similaridad_semantica_mean','similaridad_ci','vt1','vt2']]
df.columns = ['palabra','ss_mean_2009_2014','ss_ci_2009_2014','vt1_2009_2014','vt2_2009_2014']
# Período (2014, 2019)
df2 = topn_periodo[(2014, 2019)]
df2 = df2[df2['palabra'].isin(palabra_comun)]
df2 = df2[['palabra','similaridad_semantica_mean','similaridad_ci','vt1','vt2']]
df2.columns = ['palabra','ss_mean_2014_2019','ss_ci_2014_2019','vt1_2014_2019','vt2_2014_2019']
# Unión
df = df.merge(df2, how='inner', on='palabra')
df = df[['palabra', 'ss_mean_2009_2014', 'ss_mean_2014_2019', 'ss_ci_2009_2014','ss_ci_2014_2019','vt1_2009_2014','vt2_2009_2014', 'vt1_2014_2019','vt2_2014_2019']]
df['peso'] = (df['ss_mean_2009_2014'] + df['ss_mean_2014_2019'] )/2
print("Top 10 de palabras comunes con Fuerte cambio semántco entre Período [2009, 2014) - > [2014, 2019)  ")
print("Palabras:",df.sort_values('peso').head(10)['palabra'].unique() )
display(df.sort_values('peso').head(10))

Top 10 de palabras comunes con Fuerte cambio semántco entre Período [2009, 2014) - > [2014, 2019)
Palabras: ['diagnostico' 'lugar' 'instituir' 'vacuna' 'ano' 'republica' 'programa'
 'paciente' 'braille' 'especial']

,palabra,ss_mean_2009_2014,ss_mean_2014_2019,ss_ci_2009_2014,ss_ci_2014_2019,vt1_2009_2014,vt2_2009_2014,vt1_2014_2019,vt2_2014_2019,peso
57,diagnostico,-6.875000,-4.666667,"(-7.0, -6.375)","(-5.0, -4.0)","{celiaca, difusion, pmo, hepatitis, medica, tratamiento, deteccion, campana, capacitacion, psoriasis, enfermedad}","{difusion, integral, hepatitis, mujer, seguimiento, tratamiento, deteccion, capacitacion, psoriasis}","{difusion, vih, integral, hepatitis, mujer, deficit, embarazado, demas, tratamiento, deteccion, alergia, capacitacion, trombofilia, epidemiologico}","{fibromialgia, tratamiento, alergia, oncologico, sindrome, epidemiologico, investigacion}",-5.770833
122,lugar,-6.500000,-5.000000,"(-7.0, -6.0)","(-5, -5)","{exhibicion, envase, agua, bebida, perjudicial, desfibrilador, consumo, publico, externo, apto, acceso, gratuito, espacio, leyenda}","{exhibicion, tabaco, automatico, perjudicial, desfibrilador, externo, espacio}","{expendio, automatico, desfibrilador, externo, espacio}","{venta, automatico, desfibrilador, instalacion, demas, externo, privado}",-5.750000
114,instituir,-6.500000,-4.833333,"(-6.833333333333333, -6.166666666666667)","(-4.958333333333333, -4.625)","{octubre, infantil, droga, jubilado, ciudad, concientizacion, mundial, argentino, autonoma, pensionado, escolar, cancer, departamento, junio, respectivamente, mes, ano}","{octubre, diabetico, mujer, jubilado, sangre, pensionado, junio, lucha, mes, ano}","{semana, cardiopulmonar, marzo, jubilado, sangre, reanimacion, ano, mes, rcp}","{semana, marzo, cancer, afectado, lucha, mes, ano}",-5.666667
227,vacuna,-6.222222,-4.833333,"(-6.555555555555555, -5.777777777777778)","(-5.0, -4.333333333333333)","{distribucion, hepatitis, evaluacion, vacunacion, anual, produccion, leche, padecer, administracion, aplicacion, psoriasis, virus}","{distribucion, vacunacion, administracion, padecer, leche, contener, dengue, tipo, cualquiera}","{distribucion, declarese, vacunacion, administracion, padecer, leche, gratuito, alergia, dengue, cualquiera}","{prevenibl, provincia, difusion, vacunacion, prorrogable, alergia, dengue, virus}",-5.527778
9,ano,-6.000000,-5.000000,"(-6.3076923076923075, -5.6923076923076925)","(-5, -5)","{octubre, plazo, instituir, mes, sexo, volcan, movil, junio, departamento}","{octubre, instituir, menor, junio, mes}","{semana, instituir, marzo, mundial, mes}","{termino, semana, instituir, marzo, menor, prorrogable, mes}",-5.500000
199,republica,-6.333333,-4.617647,"(-6.666666666666667, -6.111111111111111)","(-4.794117647058823, -4.382352941176471)","{octubre, educacion, plazo, evaluacion, ochenta, desastre, economico, argentino, prorrogable, volcan, politica, territorio, dengue, promover}","{neuquen, negro, instalacion, argentino, junio, prorrogable, volcan, territorio, inundacion, obligacion, mes, victima}","{gastronomico, carbono, argentino, monoxido, argentina, prorrogable, territorio, victima}","{desfibrilador, evaluacion, instalacion, argentino, argentina, ciudadano, comedor}",-5.475490
180,programa,-6.187500,-4.750000,"(-6.5625, -5.8125)","(-4.916666666666667, -4.416666666666667)","{nacion, pmo, ministerio, hepatitis, evaluacion, psoriasis}","{creacion, psoriasis, pmo}","{trombofilia, pmo}","{creacion, obligatorio, nacional, plan}",-5.468750
156,paciente,-6.166667,-4.750000,"(-6.666666666666667, -5.5)","(-4.916666666666667, -4.416666666666667)","{denominado, clinico, historia, diabetico, terapia, profesional, ciudad, seguimiento, efecto, autonoma, institucion, afectado, junio}","{clinico, historia, diabetico, seguimiento, tratamiento, rehabilitacion, afectado, victima}","{clinico, historia, relacion, tratamiento, rehabilitacion, oncologico, alto, afectado, victima}","{red, donante, oncologico, institucion, victima}",-5.458333
24,braille,-5.896552,-5.000000,"(-6.103448275862069, -5.724137931034483)","(-5, -5)","{identificacion, historia, gluten, alimento, droga, sistema, rotulo, efecto, especialidad, codigo, contener, medicinal}","{identificacion, rotulo, codigo, medicinal, contenido}","{identificacion, visual, codigo, medicinal, etiquetado}","{identificacion, visual, precio, medicamento, codigo}",-5.448276
77,especial,-6.500000,-4.363636,"(-7.0, -6.0)","(-4.7272727272727275, -3.909090909090909)","{educacion, asistencia, atencion, fondo, diabetico, donacion, inundacion, cuidado, entidad, victima}","{alimenticio, asistencia, alimento, fondo, diabetico, alimentacion, donacion, gluten, ciudad, donante, nutricion, situacion}","{alimenticio, asistencia, trastorno, fondo, alimento, donacion, donante, alto, nutricion, libre}","{asignacion, educacion, fondo, respectivamente, nutricion, etiquetado}",-5.431818